/// <reference types="node" />
import assert from 'node:assert/strict';import test from 'node:test';import crypto from 'node:crypto';import {applyStarterPackRecipe,serializeStarterInventory} from './starterPackRecipe';
const slots=['weapon1','shield','helmet','chest','gloves','boots','amulet','ring','belt'];
const templates=slots.map((slot,i)=>({id:i+1,name:`item-${slot}`,slot,rarityId:2,bonuses:{s:i},extra:{crit:0},image:`${slot}.webp`}));
const essence={id:100,name:'Эссенция мрака',rarityId:3,type:'craft',image:'/essence.webp',rarityDisplay:'Редкий',rarityColor:'#00f'};
test('starter recipe атомарно добавляет 9 предметов и 4 эссенции',()=>{const result=applyStarterPackRecipe('[]',templates,[essence],()=>crypto.randomUUID());assert.equal(result.ok,true);if(!result.ok)return;assert.equal(result.inventory.length,10);assert.equal(new Set(result.inventory.slice(0,9).map(i=>i.id)).size,9);assert.equal(result.inventory[9].count,4);});
test('missing/duplicate slot или malformed template отклоняет весь starter recipe',()=>{assert.equal(applyStarterPackRecipe('[]',templates.slice(1),[essence],()=>1).ok,false);assert.equal(applyStarterPackRecipe('[]',[...templates.slice(0,8),{...templates[8],slot:'ring'} as typeof templates[number]],[essence],()=>1).ok,false);assert.equal(applyStarterPackRecipe('[]',[{...templates[0],bonuses:null as any} as typeof templates[number],...templates.slice(1)],[essence],()=>1).ok,false);});
test('duplicate/malformed essence и corrupted inventory отклоняются',()=>{assert.equal(applyStarterPackRecipe('[]',templates,[essence,{...essence,id:101}],()=>1).ok,false);assert.equal(applyStarterPackRecipe('[{"type":"craft_item","id":100,"count":-1}]',templates,[essence],()=>1).ok,false);});
test('instance IDs обязаны быть уникальными UUID',()=>{assert.equal(applyStarterPackRecipe('[]',templates,[essence],()=>1).ok,false);assert.equal(applyStarterPackRecipe('[]',templates,[essence],()=> 'not-a-uuid').ok,false);assert.equal(applyStarterPackRecipe('[]',templates,[essence],()=> '550e8400-e29b-41d4-a716-446655440000').ok,false);});
test('malformed или duplicate existing equipment IDs отклоняются',()=>{assert.equal(applyStarterPackRecipe('[{"id":"broken","slot":"ring"}]',templates,[essence],()=>crypto.randomUUID()).ok,false);const id='550e8400-e29b-41d4-a716-446655440000';assert.equal(applyStarterPackRecipe(JSON.stringify([{id,slot:'ring'},{id,slot:'belt'}]),templates,[essence],()=>crypto.randomUUID()).ok,false);});
test('legacy fractional equipment ID остаётся допустимым',()=>{const result=applyStarterPackRecipe(JSON.stringify([{id:1787440000000.25,name:'legacy',slot:'ring'}]),templates,[essence],()=>crypto.randomUUID());assert.equal(result.ok,true);});
test('legacy upgrade stack без slot остаётся допустимым',()=>{const result=applyStarterPackRecipe(JSON.stringify([{id:1787440000000.5,name:'Рунный булыжник',type:'upgrade',count:3}]),templates,[essence],()=>crypto.randomUUID());assert.equal(result.ok,true);assert.equal(applyStarterPackRecipe(JSON.stringify([{id:1787440000000.5,type:'upgrade',count:-1}]),templates,[essence],()=>crypto.randomUUID()).ok,false);});
test('repository serializer не превращает SQL NULL в пустой inventory',()=>{assert.equal(serializeStarterInventory(null),'null');assert.equal(serializeStarterInventory(undefined),'null');assert.equal(serializeStarterInventory([]),'[]');assert.equal(serializeStarterInventory('[{"id":1}]'),'[{"id":1}]');assert.equal(applyStarterPackRecipe(serializeStarterInventory(null),templates,[essence],()=>crypto.randomUUID()).ok,false);});
